apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
        name: storageos:admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: storageos-daemonset-sa
    namespace: storageos
  - kind: ServiceAccount
    name: storageos-statefulset-sa
    namespace: storageos

