apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs2
  labels:
    storageos.com/nocache: "true"
    storageos.com/throttle: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast
  resources:
    requests:
      storage: 10Gi
