kind: Pod
apiVersion: v1
metadata:
  labels:
    app: nfs-app
  name: test3
spec:
  containers:
  - name: pod
    image: ubuntu:xenial
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 3600"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs2
